// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9WqxVqG68BmDdoC5M3n3qB
// Component: tD8zdSRpzXthy
import * as React from "react";
import Link from "next/link";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import AuthorBio from "../../AuthorBio"; // plasmic-import: JdRW8IijYIt4-/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_copy_of_starter_blog_primary_copy.module.css"; // plasmic-import: 9WqxVqG68BmDdoC5M3n3qB/projectcss
import sty from "./PlasmicHomeHeader.module.css"; // plasmic-import: tD8zdSRpzXthy/css

export const PlasmicHomeHeader__VariantProps = new Array();

export const PlasmicHomeHeader__ArgProps = new Array("title");

function PlasmicHomeHeader__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <p.PlasmicLink
        data-plasmic-name={"link"}
        data-plasmic-override={overrides.link}
        className={classNames(projectcss.all, projectcss.a, sty.link)}
        component={Link}
        href={"/"}
        platform={"nextjs"}
      >
        {p.renderPlasmicSlot({
          defaultContents: "Plasmic Starter Blog",
          value: args.title,
          className: classNames(sty.slotTargetTitle)
        })}
      </p.PlasmicLink>

      <AuthorBio
        data-plasmic-name={"authorBio"}
        data-plasmic-override={overrides.authorBio}
        className={classNames("__wab_instance", sty.authorBio)}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "link", "authorBio"],
  link: ["link"],
  authorBio: ["authorBio"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomeHeader__ArgProps,
      internalVariantPropNames: PlasmicHomeHeader__VariantProps
    });

    return PlasmicHomeHeader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomeHeader";
  } else {
    func.displayName = `PlasmicHomeHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicHomeHeader = Object.assign(
  // Top-level PlasmicHomeHeader renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    link: makeNodeComponent("link"),
    authorBio: makeNodeComponent("authorBio"),
    // Metadata about props expected for PlasmicHomeHeader
    internalVariantProps: PlasmicHomeHeader__VariantProps,
    internalArgProps: PlasmicHomeHeader__ArgProps
  }
);

export default PlasmicHomeHeader;
/* prettier-ignore-end */
